### ISSUE TITLE
Browser source doesn't show anything with some versions of CEF

### ISSUE THREAD

**Issue by copygirl** [bazukas/obs-linuxbrowser#63] opened 2018-05-12 23:15 UTC
––––––––––––––––––––––
Edit from maintainer

# CEF builds that are working properly:

* 3.3440.1805
* 3.3440.1803
* 3.3325.1750

If you have successfully run obs-linuxbrowser with other CEF builds, we'd be glad, if you'd post them in this thread so we can add them to this list.
––––––––––––––––––––––

I think at some point I updated / recompiled OBS Studio from source and the linuxbrowser plugin stopped working for me and I simply don't see the browser source in the preview area. In the past I may have just had to recompile the plugin and CEF again, but not having that luck this time. Any ideas what might be wrong?

OBS log file: https://hastebin.com/oronevikac
Additional error in terminal: https://hastebin.com/omegukokuq.m

OS: Arch Linux
[`obs-studio-git`](https://aur.archlinux.org/packages/obs-studio-git/) 21.1.1.r93.gb41ca1ca
[`obs-linuxbrowser`](https://aur.archlinux.org/packages/obs-linuxbrowser/) 0.3.1-1 (Just recompiled now, so commit `2b0319a`)
[`cef-minimal`](https://aur.archlinux.org/packages/cef-minimal/) 3.3359.1772.gd1df190-1

**edit:** Appears to be an issue with recent versions of CEF, actually. No issues when using `3.3325.1750.gaabe4c4`.

**Comment by LJensrud** [comment] 2018-05-14 14:18
I have the exact same issue. I tried to downgrade to 20.0.1 just to see if that fixed the problem. No luck

**Comment by bazukas** [comment] 2018-05-14 15:59
Hello. Unfortunately I don't really understand what happened. Could you try uninstalling linuxbrowser packages and manually ~/.config/obs-studio/plugins if there are any files there.
Then installing that aur package again or just building yourself?

**Comment by yurwpjt** [comment] 2018-05-14 21:30
@bazukas I tried this way many times and it's not working.

**Comment by bazukas** [comment] 2018-05-14 21:32
@NexAdn could you please try to reproduce this error, unfortunately I no longer have an arch system

**Comment by yurwpjt** [comment] 2018-05-14 21:39
@bazukas Where are you from? (don't reply if too personal) If we're in the same country you or your friend can tell me the solution in our language.

**Comment by bazukas** [comment] 2018-05-14 21:40
@yurwpjt there is no solution yet, we're trying to figure it out

**Comment by copygirl** [comment] 2018-05-15 09:12
`~/.config/obs-studio/plugins` does not exist. `obs-linuxbrowser` installs to `/usr/lib/obs-plugins/obs-linuxbrowser.so` and `/usr/share/obs/obs-plugins/obs-linuxbrowser/`. After removing the package, those files are gone. Had no luck with reinstalling.

**Comment by copygirl** [comment] 2018-05-15 09:30
Alright, I installed an old version of the `cef-minimal` package, version `3.3325.1750.gaabe4c4` from 2018-03-18 instead of `3.3359.1772.gd1df190`. That ended up working out for me.

**Comment by bazukas** [comment] 2018-05-15 09:56
@copygirl thanks for the info, seems like the problem lies in certain versions of cef

**Comment by yurwpjt** [comment] 2018-05-15 14:47
How can i install an old version of cef-minimal in arch? @copygirl

**Comment by yurwpjt** [comment] 2018-05-15 15:12
@copygirl Worked for me, ty dude

**Comment by LJensrud** [comment] 2018-05-15 16:32
I just removed cef-minimal completely and that fixed my issue

**Comment by NexAdn** [comment] 2018-05-15 18:08
I encounter the same problem when installing some specific CEF builds, but I didn't figure out what makes CEF crash, neither did I figure out if the browser is crashing or if the rendering engine is not working correctly. The latest version that worked for me was `3.3359.1769.gd0bfc4d` if I remember correctly (I am not on my desktop right now so I can't verify).

If I encounter this problem again, I could try to debug it.

**Comment by NexAdn** [comment] 2018-05-18 13:09
This problem seems to be unrelated with obs-linuxbrowser. Even obs-browser recommends only certain CEF versions, so I think this is somehow CEF-related and nothing we can prevent.

**Comment by nocivus** [comment] 2018-05-18 14:48
Is this related to the issue i'm getting now?

```#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffd6338b6f0#0 0x7f2ebcf0421c [0518/154712.464131:WARNING:x11_util.cc(1362)] X error received: serial 63, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
base::debug::StackTrace::StackTrace()
#1 0x7f2ebf693edb gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f2ebf4e0238 V8_Fatal()
#3 0x7f2ebc576c7b v8::Isolate::New()
#4 0x7f2ebf6900b4 gin::IsolateHolder::IsolateHolder()
#5 0x7f2ebf51e265 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f2ebf51e705 blink::V8PerIsolateData::Initialize()
#7 0x7f2ebf2e876a blink::V8Initializer::InitializeMainThread()
#8 0x7f2ebf2b588f _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f2ec06c0916 content::RenderThreadImpl::Init()
#10 0x7f2ec06bf828 content::RenderThreadImpl::Create()
#11 0x7f2ec06eef87 content::RendererMain()
#12 0x7f2ebcd7d50a content::ContentMainRunnerImpl::Run()
#13 0x7f2ebe019ff5 service_manager::MainRun()
#14 0x7f2ebcdafd90 CefContext::Initialize()
#15 0x7f2ebcdafa60 CefInitialize()
#16 0x7f2ebb53cf70 cef_initialize
#17 0x558aac2baab4 CefInitialize()
#18 0x558aac2a8c63 main
#19 0x7f2eb86b81c1 __libc_start_main
#20 0x558aac2a941a _start```

Also don't see anything on the browser preview...

**Comment by NexAdn** [comment] 2018-05-18 15:41
Seems to be related. The OP has uploaded a similar log file. CEF version `3.3359.1769` is the last known version that is supposed to be working.

**Comment by NexAdn** [comment] 2018-05-18 20:48
I'll see what I can do. Atm there's a known issues section in the Readme, where I described this error and linked this issue for people to see what cef versions are known to be working.

**Comment by NexAdn** [comment] 2018-05-21 15:45
I couldn't find any classes, methods or callbacks I could use to catch log messages, but that seems to be a problem many CEF users are facing. I could monitor the log file, but parsing it is quite resource heavy for a small OBS plugin, so it's in my opinion not an option.

**Comment by puffnfresh** [comment] 2018-05-29 02:09
I can confirm version 3.3325.1750.gaabe4c4 works.

**Comment by NexAdn** [comment] 2018-05-29 14:53
There is already a known issues section in the readme.

**Comment by bennetgallein** [comment] 2018-06-07 17:45
For some reason the awnser of @LJensrud worked for me. Makes no sense to me, but it works.

**Comment by NexAdn** [comment] 2018-06-07 18:35
As obs-linuxbrowser comes with  a bundled version of cef that is known to be working, it does totally make sense. You should only encounter problems if you keep your cef-minimal installation to get recent updates. Unfortunately, I updated the AUR before I checked if the current version is working.

**Comment by iluxonchik** [comment] 2018-07-27 06:36
For those who want a step-by-step tutorial on downgrading to the version `3.3359.1769.gd0bfc4d`:

```
cd /tmp/
wget https://aur.archlinux.org/cgit/aur.git/snapshot/aur-201f7460294bfb35fffb826d71442de053dd5d74.tar.gz
tar -xf aur-201f7460294bfb35fffb826d71442de053dd5d74.tar.gz
cd aur-201f7460294bfb35fffb826d71442de053dd5d74
makepkg
pacman -U cef-minimal-3.3359.1769.gd0bfc4d-1-x86_64.pkg.tar.xz
```

If you want to upgrade/downgrade to another version of `cef-minimal`, you can find them [here](https://aur.archlinux.org/cgit/aur.git/log/?h=cef-minimal). In that case, you would have to `wget` a different `tar.gz` achieve. The commands above will be the same, but the file names will change.

**Comment by lulou** [comment] 2018-07-31 19:30
Using master for obs-studio and obs-linuxbrowser.
Having this error even with 3.3359.1769 standart on debian stable.

```info: ------------------------------------------------


#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffc14ac0360#0 0x7f9b8f231c5c base::debug::StackTrace::StackTrace()
#1 0x7f9b919c219b 

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffc39424eb0#0 0x7fe9a33d3c5c gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f9b9180e4f8 base::debug::StackTrace::StackTrace()
#1 0x7fe9a5b6419b gin::(anonymous namespace)::PrintStackTrace()
#2 0x7fe9a59b04f8 

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7fff993de550#0 0x7f05490cbc5c V8_Fatal()
#3 0x7fe9a2a46ceb V8_Fatal()
#3 0x7f9b8e8a4ceb base::debug::StackTrace::StackTrace()
#1 0x7f054b85c19b v8::Isolate::New()
#4 0x7fe9a5b60374 gin::(anonymous namespace)::PrintStackTrace()
#2gin::IsolateHolder::IsolateHolder()
#5 0x7fe9a59ee525 v8::Isolate::New()
#4 0x7f9b919be374  0x7f054b6a84f8 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7fe9a59ee9c5 gin::IsolateHolder::IsolateHolder()
#5 0x7f9b9184c525 V8_Fatal()
#3 0x7f054873eceb blink::V8PerIsolateData::Initialize()
#7 0x7fe9a57b8a2a blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f9b9184c9c5 blink::V8Initializer::InitializeMainThread()
#8 0x7fe9a5785b4f blink::V8PerIsolateData::Initialize()
#7 0x7f9b91616a2a 

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffe672f7e80#0 0x7f23c0ad5c5c v8::Isolate::New()
#4 0x7f054b858374 _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7fe9a6b91006 base::debug::StackTrace::StackTrace()
#1 0x7f23c326619b gin::IsolateHolder::IsolateHolder()
#5 0x7f054b6e6525 content::RenderThreadImpl::Init()
#10 0x7fe9a6b8ff18 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f054b6e69c5 blink::V8Initializer::InitializeMainThread()
#8 gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f23c30b24f8 0x7f9b915e3b4f content::RenderThreadImpl::Create()
#11 0x7fe9a6bbf677 blink::V8PerIsolateData::Initialize()
#7 0x7f054b4b0a2a content::RendererMain()
#12 0x7fe9a324cfaa V8_Fatal()error: A sprite cannot be drawn without a width/height

#3 0x7f23c0148ceb content::ContentMainRunnerImpl::Run()
#13 0x7fe9a44ea3d5 _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f9b929ef006 service_manager::MainRun()
#14 0x7fe9a327f810 error: A sprite cannot be drawn without a width/height
blink::V8Initializer::InitializeMainThread()
#CefContext::Initialize()
#15 0x7fe9a327f4e0 v8::Isolate::New()
#4 0x7f23c3262374 8 0x7f054b47db4f CefInitialize()
#16 0x7fe9a1a0cf70 content::RenderThreadImpl::Init()
#10 0x7f9b929edf18 gin::IsolateHolder::IsolateHolder()
#5 0x7f23c30f0525 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f23c30f09c5 _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f054c889006 cef_initialize
#17 0x55ba6c5f76e4 CefInitialize()
#18 0x55ba6c5e505b main
#19 0x7fe99ec1c2e1 __libc_start_main
#20 0x55ba6c5e581a _start
error: A sprite cannot be drawn without a width/height
content::RenderThreadImpl::Init()
#10 0x7f054c887f18 blink::V8PerIsolateData::Initialize()
#7 0x7f23c2ebaa2a content::RenderThreadImpl::Create()
#11 0x7f9b92a1d677 blink::V8Initializer::InitializeMainThread()
#8 0x7f23c2e87b4f error: A sprite cannot be drawn without a width/height
content::RendererMain()
#12 0x7f9b8f0aafaa _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f23c4293006 error: A sprite cannot be drawn without a width/height
content::RenderThreadImpl::Create()
#11 0x7f054c8b7677 content::RenderThreadImpl::Init()
#10 0x7f23c4291f18 content::ContentMainRunnerImpl::Run()
#13 0x7f9b903483d5 content::RendererMain()
#12 0x7f0548f44faa content::RenderThreadImpl::Create()
#11 0x7f23c42c1677 service_manager::MainRun()
#14 0x7f9b8f0dd810 content::ContentMainRunnerImpl::Run()
#13 0x7f054a1e23d5 CefContext::Initialize()
#15 0x7f9b8f0dd4e0 content::RendererMain()
#12 0x7f23c094efaa CefInitialize()
#16 0x7f9b8d86af70 content::ContentMainRunnerImpl::Run()
#13 0x7f23c1bec3d5 service_manager::MainRun()
#14 0x7f0548f77810 CefContext::Initialize()
#15 0x7f0548f774e0 service_manager::MainRun()
#14 0x7f23c0981810 cef_initialize
#17 0x5606c464d6e4 CefInitialize()
#18 0x5606c463b05b main
#19 0x7f9b8aa7a2e1 __libc_start_main
#20 0x5606c463b81a _start
CefContext::Initialize()
#15 0x7f23c09814e0 CefInitialize()
#16 0x7f0547704f70 CefInitialize()
#16 0x7f23bf10ef70 cef_initialize
#17 0x55bbf5a046e4 CefInitialize()
#18 0x55bbf59f205b main
#19 0x7f05449142e1 __libc_start_main
#20 0x55bbf59f281a _start
cef_initialize
#17 0x55b290b716e4 CefInitialize()
#18 0x55b290b5f05b main
#19 0x7f23bc31e2e1 __libc_start_main
#20 0x55b290b5f81a _start
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2225, resource id: 98566236, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2260, resource id: 98566236, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2263, resource id: 98566236, major code: 130 (Unknown), minor code: 3
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height
error: A sprite cannot be drawn without a width/height


#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffe672f7e80#0 0x7f23c0ad5c5c [0731/211900.870923:WARNING:x11_util.cc(1362)] X error received: serial 35, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
base::debug::StackTrace::StackTrace()
#1 0x7f23c326619b gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f23c30b24f8 V8_Fatal()
#3 0x7f23c0148ceb error: A sprite cannot be drawn without a width/height
v8::Isolate::New()
#4 0x7f23c3262374 gin::IsolateHolder::IsolateHolder()
#5 0x7f23c30f0525 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f23c30f09c5 blink::V8PerIsolateData::Initialize()
#7 0x7f23c2ebaa2a error: A sprite cannot be drawn without a width/height
blink::V8Initializer::InitializeMainThread()
#8 0x7f23c2e87b4f _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f23c4293006 content::RenderThreadImpl::Init()
#10 0x7f23c4291f18 error: A sprite cannot be drawn without a width/height
content::RenderThreadImpl::Create()
#11 0x7f23c42c1677 content::RendererMain()
#12 0x7f23c094efaa content::ContentMainRunnerImpl::Run()
#13 0x7f23c1bec3d5 service_manager::MainRun()
#14 0x7f23c0981810 CefContext::Initialize()
#15 0x7f23c09814e0 CefInitialize()
#16 0x7f23bf10ef70 cef_initialize
#17 0x55b290b716e4 CefInitialize()
#18 0x55b290b5f05b main
#19 0x7f23bc31e2e1 __libc_start_main
#20 0x55b290b5f81a _start


#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffc39424eb0#0 0x7fe9a33d3c5c base::debug::StackTrace::StackTrace()
#1 0x7fe9a5b6419b gin::(anonymous namespace)::PrintStackTrace()
#2 0x7fe9a59b04f8 V8_Fatal()
#3 0x7fe9a2a46ceb v8::Isolate::New()
#4 0x7fe9a5b60374 gin::IsolateHolder::IsolateHolder()
#5 0x7fe9a59ee525 blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7fe9a59ee9c5 blink::V8PerIsolateData::Initialize()
#7 0x7fe9a57b8a2a blink::V8Initializer::InitializeMainThread()
#8 0x7fe9a5785b4f _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7fe9a6b91006 content::RenderThreadImpl::Init()
#10 0x7fe9a6b8ff18 content::RenderThreadImpl::Create()
#11 0x7fe9a6bbf677 content::RendererMain()
#12 0x7fe9a324cfaa content::ContentMainRunnerImpl::Run()
#13 0x7fe9a44ea3d5 service_manager::MainRun()
#14 0x7fe9a327f810 CefContext::Initialize()
#15 0x7fe9a327f4e0 CefInitialize()
#16 0x7fe9a1a0cf70 cef_initialize
#17 0x55ba6c5f76e4 CefInitialize()
#18 0x55ba6c5e505b main
#19 0x7fe99ec1c2e1 __libc_start_main
#20 0x55ba6c5e581a _start


#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7ffc14ac0360#0 0x7f9b8f231c5c base::debug::StackTrace::StackTrace()
#1 0x7f9b919c219b gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f9b9180e4f8 V8_Fatal()
#3 0x7f9b8e8a4ceb 

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 0x7fff993de550#0 0x7f05490cbc5c v8::Isolate::New()
#4 0x7f9b919be374 gin::IsolateHolder::IsolateHolder()
#5 0x7f9b9184c525 base::debug::StackTrace::StackTrace()
#1 0x7f054b85c19b blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f9b9184c9c5 gin::(anonymous namespace)::PrintStackTrace()
#2 0x7f054b6a84f8 V8_Fatal()
#3 0x7f054873eceb blink::V8PerIsolateData::Initialize()
#7 0x7f9b91616a2a v8::Isolate::New()
#4 0x7f054b858374 gin::IsolateHolder::IsolateHolder()
#5 0x7f054b6e6525 blink::V8Initializer::InitializeMainThread()
#8 0x7f9b915e3b4f blink::V8PerIsolateData::V8PerIsolateData()
#6 0x7f054b6e69c5 _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f9b929ef006 blink::V8PerIsolateData::Initialize()
#7 0x7f054b4b0a2a content::RenderThreadImpl::Init()
#10 0x7f9b929edf18 blink::V8Initializer::InitializeMainThread()
#8 0x7f054b47db4f content::RenderThreadImpl::Create()
#11 0x7f9b92a1d677 _ZN5blink10InitializeEPNS_8PlatformEPN15service_manager22BinderRegistryWithArgsIJEEE
#9 0x7f054c889006 content::RendererMain()
#12 0x7f9b8f0aafaa content::RenderThreadImpl::Init()
#10 0x7f054c887f18 content::ContentMainRunnerImpl::Run()
#13 0x7f9b903483d5 service_manager::MainRun()
#14 0x7f9b8f0dd810 content::RenderThreadImpl::Create()
#11 0x7f054c8b7677 CefContext::Initialize()
#15 0x7f9b8f0dd4e0 CefInitialize()
#16 0x7f9b8d86af70 content::RendererMain()
#12 0x7f0548f44faa content::ContentMainRunnerImpl::Run()
#13 0x7f054a1e23d5 cef_initialize
#17 0x5606c464d6e4 CefInitialize()
#18 0x5606c463b05b main
#19 0x7f9b8aa7a2e1 __libc_start_main
#20 0x5606c463b81a _start
service_manager::MainRun()
#14 0x7f0548f77810 CefContext::Initialize()
#15 0x7f0548f774e0 CefInitialize()
#16 0x7f0547704f70 cef_initialize
#17 0x55bbf5a046e4 CefInitialize()
#18 0x55bbf59f205b main
#19 0x7f05449142e1 __libc_start_main
#20 0x55bbf59f281a _start
```

**Comment by NexAdn** [comment] 2018-07-31 19:39
Did you try using 1750?

**Comment by lulou** [comment] 2018-07-31 20:16
Yes sir, this is working.

By the way: https://obsproject.com/forum/threads/obs-tcl-build-script.92217/ I just wrote this while it was compiling. Recompiling with a different version takes arround 5 minutes. Tell me what version I should test if you want.

**Comment by NexAdn** [comment] 2018-08-01 03:31
For now, I removed 1769 from the list of working versions.

**Comment by accidentalrebel** [comment] 2018-08-06 23:12
This combination does not work. Linux browser is blank:

- obs-linuxbrowser 0.5.0-1
- obs-studio 21.1.2-1
- cef-minimal 3.3325.1750.gaabe4c4-1

Should I switch from `obs-studio` to `obs-studio-git`? Also, where do I see the logs?

**Comment by accidentalrebel** [comment] 2018-08-07 13:57
Was able to generate the logs. The error seemed to happen on this part:
```
info: User added source 'Linux Browser' (linuxbrowser-source) to scene 'Scene'
/usr//lib/obs-plugins/browser: symbol lookup error: /usr//lib/obs-plugins/browser: undefined symbol: cef_v8value_create_array_buffer
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5537, resource id: 4198060, major code: 40 (TranslateCoords), minor code: 0
```

Not sure what it means though.

**Comment by NexAdn** [comment] 2018-08-27 01:32
Confirmed 1805.

**Comment by lulou** [comment] 2018-08-27 19:02
Confirmed cef1805/obs22.0.1 on debian 9 stable

**Comment by NexAdn** [comment] 2018-08-27 20:33
Confirmed 1802 – 1769.

I think #79 actually resolved the issue. At least, the most recent builds seem to be working fine. I'll close this issue for now.

**Closed by NexAdn** 2018-08-27 20:33 UTC
Labels: bug

**Comment by accidentalrebel** [comment] 2018-08-28 06:35
Recent builds now works. Thanks a lot!

**Comment by NexAdn** [comment] 2019-01-16 10:05
Issues #93, #95, #87 and #94 might be related.

I've also read that there might be problems when shipping both `snapshot_blob.bin` and `v8_context_snapshot.bin`. I will reopen this issue if the relation is confirmed.
