### ISSUE TITLE
Which version of obs-linuxbrowser?

### ISSUE THREAD

**Issue by networkcookie** [bazukas/obs-linuxbrowser#86] opened 2018-09-07 09:00 UTC
I've updated my obs and it's telling me that it's already the newest version (0.15.4+dfsg1-1+b1) so which obs-linuxbrowser version do I need? linuxbrowser0.5.2-obs21.1.2-64bit is for obs version 21.1.2 right?

**Comment by NexAdn** [comment] 2018-09-07 09:09
Are you using old OBS Classic or OBS Studio? As stated in the README, this plugin is for OBS Studio and I highly doubt that it will work with OBS Classic. If you are indeed using OBS Classic, you should switch to OBS Studio if you intend to use our plugin. If you are actually using OBS Studio, then whatever package manager you are using, it's using a version numbering system that does not match with the one of OBS Studio. In this case I suggest checking the version number in the title bar of your OBS Studio window.

Ultimately, you can try compiling our plugin from source with your current OBS installation. This should always work, given that you are using OBS Studio.

**Comment by RytoEX** [comment] 2018-09-07 09:19
There is no OBS Classic for Linux.  OBS Classic was Windows only.

Sounds more like an outdated package.  Looks like [the Debian Stretch package](https://packages.debian.org/stretch/video/obs-studio).  Not even [Buster and Sid](https://packages.debian.org/search?keywords=obs-studio) currently have OBS Studio 22.x.

**Comment by networkcookie** [comment] 2018-09-07 10:37
I did "apt install obs-studio" and it told me that I have the newest version, so I guess I don't have classic.

**Comment by NexAdn** [comment] 2018-09-09 18:13
Package: obs-studio (21.1.2+dfsg1-1 and others)

That's what I got from a short lookup on the debian webite. Apparently, their version (for Sid) seems to be 21.1.2 which is not the latest version, but still not very old. Maybe there is some repository/mirror in your apt config that provides you with an outdated version? Stretch seems to have this version 0.15 (is this a beta/dev version of OBS Studio?). Maybe you can fix this by changing the repository mirror providing obs-studio.

I'll be happy if you'd post your solution given that it is not caused by a custom configuration to help others who might also encounter your issue.

Nonetheless, as this is not related to our plugin, I'll close this issue for now.

**Closed by NexAdn** 2018-09-09 18:13 UTC

**Comment by RytoEX** [comment] 2018-09-10 02:30
@NexAdn 
As I mentioned above, Debian 9 ("Stretch", the current stable release of Debian) provides OBS Studio 0.15.4 in the Debian package repository, just as the Debian package repository offers 21.1.2 for Buster and Sid.  I couldn't tell you why they offer those versions.

[OBS Studio 0.15.4](https://github.com/obsproject/obs-studio/releases/tag/0.15.4) isn't a beta or dev version, that's simply the version numbering scheme used before OBS Studio 17.0.0.  If I recall correctly, Jim used 0.x.x because he felt that it shouldn't reach 1.x.x until it reached feature parity with OBS Classic.  Around the OBS Studio 17.0.0 release, Jim decided the version numbers would be better with a non-zero as the first number for a variety of reasons, so the version jumped from 0.16.6 to 17.0.0.

As I understand it, the only official Linux package currently maintained by OBS contributors is the [Ubuntu PPA](https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio).  For any other Linux distributions, it's currently up to their package maintainers to provide up-to-date packages, or for users to build obs-studio from source.

**Comment by networkcookie** [comment] 2018-09-22 18:59
Tried it with release 0.4.1 20.1.1 to 0.5.2 21.1.2, obs still won't start with the plugin
