### ISSUE TITLE
Sound capture?

### ISSUE THREAD

**Issue by egordorichev** [bazukas/obs-linuxbrowser#10] opened 2017-04-17 15:20 UTC

**Comment by bazukas** [comment] 2017-04-17 15:26
Can you elaborate a little bit more, please? Cef currently plays audio on your desktop which you can capture in obs just fine.

**Comment by egordorichev** [comment] 2017-04-17 15:33
Sorry. Here is more info:

I have a app, that runs on node js like a server. It serves a web page with audio files, played using js.
I i use my chrome, the sounds are in place. But in OBS, sounds are not audible.

**Comment by bazukas** [comment] 2017-04-17 15:34
What type of audio are you playing? mp3?

**Comment by egordorichev** [comment] 2017-04-17 15:35
mp3 and wav.

**Comment by egordorichev** [comment] 2017-04-17 15:36
my system runs pulseaudio.

**Comment by bazukas** [comment] 2017-04-17 15:37
Not sure about wav, but there is no support for mp3 out of the box in cef, sorry. Try converting your files to .ogg
Alternatively you could use a flash player to play the sounds.

**Comment by egordorichev** [comment] 2017-04-17 15:37
Ok, will try that and notice you.

**Comment by egordorichev** [comment] 2017-04-17 15:42
Great, now it works. Sorry for distributing.

**Comment by egordorichev** [comment] 2017-04-17 15:46
By the way, there is still some errors in console:

```
[0417/184330.199206:INFO:CONSOLE(0)] "Uncaught (in promise) EncodingError: Unable to decode audio data", source: http://localhost:8080/ (0)
```

**Comment by bazukas** [comment] 2017-04-17 16:03
Those messages are printed by the js code, unfortunately I can't tell what's the problem without a context. Are you sure this is related to the plugin?

**Comment by egordorichev** [comment] 2017-04-17 16:04
I think so. Why else it plays ok in chrome?

**Comment by bazukas** [comment] 2017-04-17 16:05
What are you trying to do?

**Comment by egordorichev** [comment] 2017-04-17 16:13
I'm playing sounds using p5.js library. It is build in into a mini-game.

**Comment by bazukas** [comment] 2017-04-17 16:15
Could you provide an example page that produces the error, which I can test the plugin with?

**Comment by egordorichev** [comment] 2017-04-17 16:16
Live? Or just the code?

**Comment by bazukas** [comment] 2017-04-17 16:20
Either hosted online or just files that I can download and test locally

**Comment by egordorichev** [comment] 2017-04-17 16:33
http://5.19.138.134:8080/

**Comment by egordorichev** [comment] 2017-04-17 16:34
You should here the explode sound.

**Comment by bazukas** [comment] 2017-04-17 16:38
It's playing mp3 files though.

**Comment by egordorichev** [comment] 2017-04-17 16:39
You sad that they should work, did not you?

**Comment by bazukas** [comment] 2017-04-17 16:40
No, there is no support for mp3 out of box, I suggested trying ogg format.

**Comment by egordorichev** [comment] 2017-04-17 16:41
Oh, it is my error. Sorry again.

**Comment by egordorichev** [comment] 2017-04-18 13:11
Not working at all. Tested all types of sounds.

**Comment by bazukas** [comment] 2017-04-18 13:19
Please stop closing-reopening the issue until you confirmed that it is solved. Saying that it "doesn't work" also does not help me to diagnose the problem. Please provide a page which I can open and see what's the problem.

**Comment by egordorichev** [comment] 2017-04-18 13:32
http://5.19.138.134:8080/ If it not loading, try to reload a few times. Sorry for this issue-mess.

**Comment by bazukas** [comment] 2017-04-18 13:59
I can't replicate the issue over at my end. Sounds play on loading the page.

Check if there are any errors in obs log. Also you can install pavucontrol and see what applications try to play sounds. Browser source should shop up as chromium

**Comment by egordorichev** [comment] 2017-04-18 14:55
So here is the thing: I have audio playing in the OBS. But my stream does not receive sounds. Media sources, like music are playing, but sounds from the browser are muted or something. No extra audio channels appears in the mixer.

**Comment by bazukas** [comment] 2017-04-18 15:24
I don't quite get what you are implying. I assume you can hear the sound coming from you default pulseaudio device? In order to capture that you need to use pulseaudio output capture source.

**Comment by egordorichev** [comment] 2017-04-18 15:25
No. On my side sounds are in place. But they are not streamed.

**Comment by bazukas** [comment] 2017-04-18 15:27
That's the intended behavior. Do you have desktop audio capture enabled?

**Comment by egordorichev** [comment] 2017-04-18 15:28
It is not showing up anywere in the OBS menu.

**Comment by egordorichev** [comment] 2017-04-18 15:29
![screenshot_2017-04-18_18-26-50](https://cloud.githubusercontent.com/assets/7851390/25139094/f4fc50b0-2464-11e7-848c-8007aa61e0c7.png)

**Comment by bazukas** [comment] 2017-04-18 15:33
You're supposed to select a device in "Desktop Audio Device"
Is the pulseaudio-input plugin loaded?

**Comment by egordorichev** [comment] 2017-04-18 15:33
Yes. Pulse audio works just fine.

**Comment by bazukas** [comment] 2017-04-18 15:36
So does it work or not? Can you enable desktop audio capture?

**Comment by egordorichev** [comment] 2017-04-18 15:36
I can't record desktop audio at all.

**Comment by egordorichev** [comment] 2017-04-18 15:37
It only works if I connect my line out to my line in.

**Comment by bazukas** [comment] 2017-04-18 15:41
Can you add "Audio Capture Source (Pulseaudio)" in the sources list?

**Comment by egordorichev** [comment] 2017-04-18 15:42
No, only ALSA.

**Comment by bazukas** [comment] 2017-04-18 15:46
You said earlier that "pulse audio works just fine". I assumed that you meant in obs.
Since you're using gentoo, my guess is that you didn't enable pulseaudio flag when installing obs.

**Comment by bazukas** [comment] 2017-04-18 15:54
Closing the issue since the plugin works as intended

**Closed by bazukas** 2017-04-18 15:54 UTC

**Comment by bazukas** [comment] 2017-04-18 16:45
Let me know if you weren't able to get desktop audio capture to work, I'll try to provide assistance.
