### ISSUE TITLE
Allow global (multi-user) installation

### ISSUE THREAD

**Issue by Marte2007** [bazukas/obs-linuxbrowser#8] opened 2017-04-14 17:26 UTC
I am trying to make the AUR package for this plugin (https://aur.archlinux.org/packages/obs-linuxbrowser/) work from global locations, /usr/lib/obs-plugins/ and /usr/share/obs-studio/plugins/.
I am able to start OBS by putting all the files  from bin/64bit in /usr/lib/obs-plugins/, and I can see with strace that it's looking for /usr/lib/o/data/cef.pak. If I put the data dir there, it works.
I think the fault is here: https://github.com/bazukas/obs-linuxbrowser/blob/master/src/browser/browser.cpp
You are resizing the string by a fixed number of chars to get the "data" directory, is it possible to modify it so that it can find /usr/share/obs-studio/plugins/obs-linuxbrowser/ or something like that?

**Comment by bazukas** [comment] 2017-04-15 14:06
Hey there. This plugin was not designed to be installed in the "global" locations, since those are not documented and intended for the third-party plugins to be installed in, so I find your conclusion that this is a "bug" with the plugin a little bit unfair.

In any case, this shouldn't be difficult to fix, I'll look into it this weekend.

**Comment by bazukas** [comment] 2017-04-17 11:38
This should be fixed in the latest release, you can install plugin files in /usr/lib/obs-plugins and /ush/share/obs/obs-plugins and it should work just fine.

Please confirm.

**Comment by NexAdn** [comment] 2017-04-17 16:08
Confirmed. Thank you.

**Closed** 2017-04-17 16:10 UTC
