### ISSUE TITLE
Audio output to obs-mixer

### ISSUE THREAD

**Issue by sebseb7** [bazukas/obs-linuxbrowser#31] opened 2017-08-12 09:05 UTC
possible to route browser-audio to obs audio mixer?

**Comment by MichaelTunnell** [comment] 2017-08-12 19:18
you can already use your pulseaudio output device in OBS so why do you need browser audio separated if it is already a part of the pulseaudio output?

**Comment by ThePooN** [comment] 2017-08-12 20:19
You might just wanna not hear it. The output is always the default one and the only way to change it is manual with `pavucontrol`, and it saves per-process and not per-instance so if you restart all the browser process will use the same output again.
Very annoying.

AFAIK the Chrome SDK doesn't allow re-routing audio.

**Comment by bazukas** [comment] 2017-08-12 22:37
Theoretically we can set browser process to output to virtual pulseaudio sink, then capture that sink from inside the plugin and then output to obs mixer.

Problem is that most of the users need to monitor browser audio and they also capture desktop audio, so that would cause audio to be duplicated.

We could make an optional flag to not monitor the audio in which case it would be routed to obs mixer or we could wait until audio monitoring in obs is implemented for Linux.

In any case we need to make sure that plugin will work as expected for most of the users 'out of box'.

**Comment by ThePooN** [comment] 2017-08-12 22:47
Also that means users *have to* use PulseAudio.

**Comment by bazukas** [comment] 2017-08-12 22:49
It can be a compile time flag, shouldn't be a problem.

**Comment by bazukas** [comment] 2017-08-13 09:24
Duplicate of #15

**Closed by bazukas** 2017-08-13 09:24 UTC
