### ISSUE TITLE
0.6.1 not building on Ubuntu 18.04, CEF 79.0.0

### ISSUE THREAD

**Issue by ThorinWolf** [bazukas/obs-linuxbrowser#124] opened 2020-01-12 15:33 UTC
I managed to self-compile CEF with MP3 support, and copy the files to the right place (/opt/cef, makeshift install because there are literally no instructions on how to install it, so i dumped the necessary and addition files from the cefsimple directory to there), but this error occurs on building obs-linuxbrowser:
```C++
~/Downloads/obs-linuxbrowser-0.6.1/build$ make -j4
Scanning dependencies of target browser_shared
Scanning dependencies of target obs-linuxbrowser
[ 18%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o
[ 18%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/manager.c.o
[ 36%] Building CXX object CMakeFiles/browser_shared.dir/src/browser/browser-app.cpp.o
[ 36%] Building CXX object CMakeFiles/browser_shared.dir/src/browser/base64.cpp.o
[ 45%] Building CXX object CMakeFiles/browser_shared.dir/src/browser/browser-client.cpp.o
[ 54%] Linking C shared module build/obs-linuxbrowser/bin/64bit/libobs-linuxbrowser.so
[ 54%] Built target obs-linuxbrowser
[ 63%] Building CXX object CMakeFiles/browser_shared.dir/src/browser/split-message.cpp.o
In file included from /home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp:29:0:
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.hpp:76:15: error: ‘virtual bool BrowserApp::OnProcessMessageReceived(CefRefPtr<CefBrowser>, CefProcessId, CefRefPtr<CefProcessMessage>)’ marked ‘override’, but does not override
  virtual bool OnProcessMessageReceived(CefRefPtr<CefBrowser> browser,
               ^~~~~~~~~~~~~~~~~~~~~~~~
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp: In member function ‘virtual void BrowserApp::OnContextInitialized()’:
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp:316:91: error: no matching function for call to ‘CefBrowserHost::CreateBrowserSync(CefWindowInfo&, BrowserClient*, const char [45], CefBrowserSettings&, std::nullptr_t)’
      info, client.get(), "https://github.com/bazukas/obs-linuxbrowser/", settings, nullptr);
                                                                                           ^
In file included from /opt/cef/include/../include/cef_print_handler.h:42:0,
                 from /opt/cef/include/../include/cef_browser_process_handler.h:43,
                 from /opt/cef/include/cef_app.h:42,
                 from /home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.hpp:23,
                 from /home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp:29:
/opt/cef/include/../include/cef_browser.h:305:32: note: candidate: static CefRefPtr<CefBrowser> CefBrowserHost::CreateBrowserSync(const CefWindowInfo&, CefRefPtr<CefClient>, const CefString&, const CefBrowserSettings&, CefRefPtr<CefDictionaryValue>, CefRefPtr<CefRequestContext>)
   static CefRefPtr<CefBrowser> CreateBrowserSync(
                                ^~~~~~~~~~~~~~~~~
/opt/cef/include/../include/cef_browser.h:305:32: note:   candidate expects 6 arguments, 5 provided
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp: In member function ‘void BrowserApp::UpdateActiveStateJS(bool)’:
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp:387:17: error: ‘class CefBrowser’ has no member named ‘SendProcessMessage’
  this->browser->SendProcessMessage(PID_BROWSER, msg);
                 ^~~~~~~~~~~~~~~~~~
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browsneccessaryer/browser-app.cpp: In member function ‘void BrowserApp::UpdateVisibilityStateJS(bool)’:
/home/moltres/Downloads/obs-linuxbrowser-0.6.1/src/browser/browser-app.cpp:395:17: error: ‘class CefBrowser’ has no member named ‘SendProcessMessage’
  this->browser->SendProcessMessage(PID_BROWSER, msg);
                 ^~~~~~~~~~~~~~~~~~
CMakeFiles/browser_shared.dir/build.make:86: recipe for target 'CMakeFiles/browser_shared.dir/src/browser/browser-app.cpp.o' failed
make[2]: *** [CMakeFiles/browser_shared.dir/src/browser/browser-app.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/browser_shared.dir/all' failed
make[1]: *** [CMakeFiles/browser_shared.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
Have tried using your prepacked version, and copying the CEF files to the relevant parts once extracted, but the browser fails to load. Have tried forcing it to compile, but the browser never loads. Any help? (and no, I'm not gonna compile another version of CEF, it's taken me 3 days to get this version running)

**Comment by NexAdn** [comment] 2020-01-12 17:12
Duplicate of #121.

Also: CEF and Chromium are already being distributed with MP3 support in the binary release for some time now (see #18).

**Closed by NexAdn** 2020-01-12 17:12 UTC
