### ISSUE TITLE
streamlabs 22.0.3 crashes

### ISSUE THREAD

**Issue by AltQuest** [bazukas/obs-linuxbrowser#90] opened 2018-11-15 00:35 UTC
hi, im running streamlabs OBS 22.0.3 in ubuntu 16.04LTS
i had to reinstall streamlabs today and when i added the linuxbroswer
it crashes :/ wasnt sure if this was a common issue or if it was something i did?
if you need more info i can try to give. i love the project!

**Comment by lulou** [comment] 2018-11-15 09:16
At the very minimum, we need the obs logs.
Start obs in a console, and reproduce the steps to make obs crash again.
Then copy paste the console output of obs into this report.

**Comment by OsirisNL** [comment] 2018-11-16 14:03
FYI, there is no Streamlabs OBS 22.0.3, nor is there a Streamlabs OBS for Linux.

**Comment by NexAdn** [comment] 2018-11-16 17:01
Okay, that should explain everything. I suppose @AltQuest has installed SLOBS using Wine or he isn't using Linux for streaming.

Please confirm that the plugin isn't working for you when using standard OBS or keep this issue closed.

Closing this issue now as seems to be unrelated to obs-linuxbrowser itself.

**Closed by NexAdn** 2018-11-16 17:01 UTC
