### ISSUE TITLE
Pop!_OS (Ubuntu 17.10) Source does not display.

### ISSUE THREAD

**Issue by trinitrot0luene** [bazukas/obs-linuxbrowser#60] opened 2018-04-28 12:27 UTC
So I've been trying to get this plugin to run for a little while now. Since the latest release on the repo doesn't match my OBS version (21.1.0) I built the plugin myself and it appeared to install fine. 

Unfortunately the browser never starts up properly since some internal nullptr exceptions seem to be crashing the plugin. They are never shown in OBS but I've got a logfile [here.](https://transfer.sh/fQy7L/obs-log.txt) 

Would appreciate any help/guidance in resolving this. Thanks!

**Comment by NexAdn** [comment] 2018-04-28 13:49
Do you have an up to date version of CEF minimal release or higher?

**Comment by trinitrot0luene** [comment] 2018-04-28 14:35
I have the standard distribution, not the minimal one. Is that a problem?

(version for reference: 04/19/2018 - CEF 3.3359.1768.g8e7c5d6)

**Comment by trinitrot0luene** [comment] 2018-04-28 15:13
I completely deleted the plugin folder + downloaded the latest CEF minimal release, built it and then tried rebuilding + installing the plugin. 

Still doesn't appear to work. [Attached log files here.](https://transfer.sh/udIEj/obs-log.txt)

One line that seems relevant could be this? `X error received: serial 45, error_code 3 (BadWindow (invalid Window parameter))`. 


```
[0428/160346.144911:ERROR:gl_surface_glx.cc(581)] XGetWindowAttributes failed for window 111149060.
[0428/160346.144996:ERROR:gles2_command_buffer_stub.cc(226)] ContextResult::kFatalFailure: Failed to create surface.
[0428/160346.145280:WARNING:x11_util.cc(1362)] X error received: serial 353, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_Get$
```

Just some parts that might help. Maybe I haven't installed CEF correctly? The files do seem present and should be up to date through. 

In my /data/cef folder I have 
```
cef_100_percent.pak  cef_200_percent.pak  cef_extensions.pak  cef.pak  devtools_resources.pak  locales
```
and in /bin/64bit I have 
```
browser  browser-subprocess  debug.log	icudtl.dat  libcef.so  libobs-linuxbrowser.so  natives_blob.bin  snapshot_blob.bin
``` 
I'm no expert so I might be completely wrong but this looks alright to me?

**Comment by NexAdn** [comment] 2018-04-28 15:46
There seems to be a problem with the snapshot blob file, but I don't know what it is. Maybe some files are corrupt or couldn't be found/read.

**Comment by trinitrot0luene** [comment] 2018-04-30 16:27
I've deleted everything, redownloaded & built CEF + obs-linuxbrowser, and still no luck. This is a 1 week old installation so as close to mint as it could be really, so I don't know what the problem is. Is there an ETA on a prebuilt release for the latest version of OBS being published on the repo? Otherwise I think I might have to give up on making this work.

**Comment by NexAdn** [comment] 2018-04-30 16:35
You could try compiling cef manually. Maybe the binary release isn't working on pop os

**Comment by bazukas** [comment] 2018-05-14 16:05
Hello @trinitrot0luene , sorry I was unable to answer you sooner. Latest binary version should not have any problems working with 21.1.0, that's not the problem here. Unfortunately I can't read your attached log files anymore, could you reupload?
Also, can you describe how you installed obs-studio? Did you use ppa?

**Comment by trinitrot0luene** [comment] 2018-05-15 10:05
Hi, thanks for responding! I downloaded it from the ppa provided on the obs website. I ended up "fixing" the problem by deleting every obs-linuxbrowser related file (including the logs unfortunately) and just extracting the precompiled archive that @NexAdn kindly provided in #62, which ended up working just fine.

Since it seems that certain versions of cef are causing similar issues for other people too (#63) I assume this is probably a variant of that problem? 

Just for reference the cef version that I attempted this with was `3.3359.1768.g8e7c5d6`, and I tried both the minimal and full binaries of that version. 

I'll try to find the logfiles in case I did back them up elsewhere, but I'm afraid I might not be able to re-upload them.

**Comment by bazukas** [comment] 2018-05-15 10:09
It might be the same problem others have experienced in regards to certain versions of cef.
Btw, you mentioned that you tried to build the plugin since the latest release version didn't match your obs. Did you try using it anyways? Because it should work just fine.

**Comment by trinitrot0luene** [comment] 2018-05-15 10:12
Yes, I tried the release for 20.x.x provided on the repo, but the plugin wouldn't show up as installed. The version that I built locally did show up in OBS, but didn't work. My best guess is that OBS didn't like the version number :man_shrugging:

**Comment by NexAdn** [comment] 2018-05-18 14:58
Duplicate of #63. The error messages are matching perfectly with the ones that occured in #63 with certain versions of CEF.

**Closed by NexAdn** 2018-05-18 14:58 UTC
