### ISSUE TITLE
No sound in version 0.5.1

### ISSUE THREAD

**Issue by lordgault** [bazukas/obs-linuxbrowser#80] opened 2018-08-21 06:10 UTC
Hello. The new version 0.5.1 has no alert sound. Tested on the test website https://streamlabs.com/dashboard#/alertbox
The previous version 0.5.0 does work.
Use KDE Neon based on Ubuntu 18.04.
Greetings

**Comment by NexAdn** [comment] 2018-08-21 11:12
Might have something to do with #74. Although by the time that issue was opened we were using CEF build 1750 (March 2018), 0.5.1 switched to CEF build 1803 (July 2018) which means that 0.5.1 seems to be affected by the new Chrome autoplay policies.

I'll mark this issue as a duplicate of #74 and reopen the latter.

**Closed by NexAdn** 2018-08-21 11:12 UTC
Labels: bug
